---
- name: install development packages
  apt: name={{ item }} state=present
  with_items:
    - bash-completion
  tags:
    - development
    - apt

- name: copy up autocomplete config files
  copy:
    src: "etc/bash_completion.d/{{ item }}"
    dest: "/etc/bash_completion.d/{{ item }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - fab
