"""empty message

Revision ID: 2b3e533d91ba
Revises: None
Create Date: 2015-09-02 12:59:04.984894

"""

# revision identifiers, used by Alembic.
revision = '2b3e533d91ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=True),
    sa.Column('dynamic_table_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types_x_metadata_properties',
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('metadata_property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['metadata_property_id'], ['metadata_properties.id'], )
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('file_dir', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('metadata_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dynamic_table')
    op.drop_table('documents')
    op.drop_table('document_types_x_metadata_properties')
    op.drop_table('metadata_properties')
    op.drop_table('document_types')
    ### end Alembic commands ###
